format_version: 10
pipelines:
  spring_petclinic_graphql:
    group: petclinic
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-04ff57c:
        git: https://github.com/rvkhakhkhar/spring-petclinic-graphql.git
        shallow_clone: false
        auto_update: true
        branch: build-frontend
    stages:
    - Test_And_Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          backend:
            resources:
              - java-8
            tasks:
            - exec:
                arguments:
                  - -c
                  - ./mvnw clean package
                command: /bin/sh
                working_directory: backend
                run_if: passed
          fronend:
            resources:
              - node
            tasks:
              - exec:
                  arguments:
                    - -c
                    - yarn install
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - yarn install
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed