format_version: 10
pipelines:
  spring_petclinic_graphql:
    group: petclinic
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-04ff57c:
        git: https://github.com/rvkhakhkhar/spring-petclinic-graphql.git
        shallow_clone: false
        auto_update: true
        branch: backend-image-push
    stages:
    - Test_And_Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build_Backend:
            resources:
              - java-8
            artifacts:
              - build:
                  source: backend/target/spring-petclinic-2.0.0.war
                  destination: backend-artifact/spring-petclinic-2.0.0.war
            tasks:
            - exec:
                arguments:
                  - -c
                  - ./mvnw clean package
                command: /bin/sh
                working_directory: backend
                run_if: passed
          Build_Frontend:
            resources:
              - node
            tasks:
              - exec:
                  arguments:
                    - -c
                    - yarn install
                    - yarn run dist
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed
    - Build_And_Push_Image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Build_And_Push_Image_Backend:
            timeout: 0
            resources:
              - docker
            secure_variables:
              AWS_ACCESS_KEY_ID: AES:04dd7rTO5rovU0mS/E5slA==:VHGOzyt+QUE5aE3UMsdW2aYpIJ52o9WUJtWa3gcEZf1zEaF/v0ycJdlGCc77ihXg
              AWS_SECRET_ACCESS_KEY: AES:whwiqjkpSaMxa4WIdvf8Yw==:887FhSi0ll0d/eZhvYwlbVqkf22eX089rmmpwbPg2OnGfLZYqekyqb/MpAKy8imf
            tasks:
              - fetch:
                  is_file: false
                  source: backend-artifact/spring-petclinic-2.0.0.war
                  destination: backend/target/spring-petclinic-2.0.0.war
                  pipeline: spring_petclinic_graphql
                  stage: Test_And_Build
                  job: Build_Backend
                  artifact_origin: gocd
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - docker build -t gocd-petclinic-backend .
                  command: /bin/sh
                  working_directory: backend
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - aws ecr get-login-password --region us-east-1
                  command: /bin/sh
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - 'aws ecr describe-repositories --repository-names gocd-petclinic-backend
                    --region us-east-1 || aws ecr create-repository --repository-name
                    gocd-petclinic-backend --image-tag-mutability IMMUTABLE --region
                    us-east-1 '
                  command: /bin/sh
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - docker tag gocd-petclinic-backend:latest 038062473746.dkr.ecr.us-east-1.amazonaws.com/gocd-petclinic-backend:${GO_LABEL}-${GO_REVISION}
                  command: /bin/sh
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - docker push 038062473746.dkr.ecr.us-east-1.amazonaws.com/gocd-petclinic-backend:${GO_LABEL}-${GO_REVISION}
                  command: /bin/sh
                  run_if: passed
          Build_Image_Frontend:
            timeout: 0
            resources:
              - docker
            tasks:
              - exec:
                  arguments:
                    - -c
                    - docker build -t petclinic-frontend:latest .
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed