format_version: 10
pipelines:
  spring_petclinic_graphql:
    group: petclinic
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-04ff57c:
        git: https://github.com/rvkhakhkhar/spring-petclinic-graphql.git
        shallow_clone: false
        auto_update: true
        branch: build-backend
    stages:
    - Test And Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          backend:
            resources:
              - java-8
            tasks:
            - exec:
                command: cd backend && ./mvnw clean package
                run_if: passed
