format_version: 10
pipelines:
  spring_petclinic_graphql:
    group: petclinic
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-04ff57c:
        git: https://github.com/rvkhakhkhar/spring-petclinic-graphql.git
        shallow_clone: false
        auto_update: true
        branch: build-docker-image
    stages:
    - Test_And_Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build_Backend:
            resources:
              - java-8
            artifacts:
              - build:
                  source: backend/target/spring-petclinic-2.0.0.war
                  destination: backend-artifact/spring-petclinic-2.0.0.war
            tasks:
            - exec:
                arguments:
                  - -c
                  - ./mvnw clean package
                command: /bin/sh
                working_directory: backend
                run_if: passed
          Build_Frontend:
            resources:
              - node
            tasks:
              - exec:
                  arguments:
                    - -c
                    - yarn install
                    - yarn run dist
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed
    - Build_Image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Build_Image_Backend:
            timeout: 0
            resources:
              - docker
            tasks:
              - fetch:
                  is_file: false
                  source: backend-artifact/spring-petclinic-2.0.0.war
                  destination: backend/target/spring-petclinic-2.0.0.war
                  pipeline: petclinic-manual
                  stage: Test_And_Build
                  job: Build_Backend
                  artifact_origin: gocd
                  run_if: passed
              - exec:
                  arguments:
                    - -c
                    - docker build -t petclinic-backend:latest .
                  command: /bin/sh
                  working_directory: backend
                  run_if: passed
          Build_Image_Frontend:
            timeout: 0
            resources:
              - docker
            tasks:
              - exec:
                  arguments:
                    - -c
                    - docker build -t petclinic-frontend:latest .
                  command: /bin/sh
                  working_directory: frontend
                  run_if: passed